version: "3.8"

volumes:
  .volumes:

services:
  postgres:
    image: postgres:16
    container_name: postgres
    hostname: postgres
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./.volumes/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
    command: ["postgres", "-c", "log_statement=all"]

  mongo:
    image: bitnami/mongodb:latest
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
      MONGODB_REPLICA_SET_MODE: "primary"
      MONGODB_REPLICA_SET_KEY: "replicaset"
      MONGODB_ADVERTISED_HOSTNAME: ${MONGO_HOST}
      MONGODB_ADVERTISED_PORT_NUMBER: ${MONGO_PORT}
      MONGODB_ROOT_USER: ${MONGO_ROOT_USER}
      MONGODB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGODB_USERNAME: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_DATABASE: ${MONGO_DB}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
    volumes:
      - ./.volumes/mongodata:/data/db

  minio:
    container_name: minio
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${S3_LOGIN}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.volumes/miniodata:/data
    command: server --console-address ":9001" /data
